name: Auto commit

on:
  schedule:
    - cron: '0,30 * * * *'

jobs:
  auto_commit:
    name: 'Auto push a commit to my repo'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create sample file with just timestamp
      run: date +%s >> report.txt
    - name: Commit file
      run: |
          git config --global user.name 'Automated Tomidiyu'
          git config --global user.email 'super-novey@users.noreply.github.com'
          git add report.txt
          git commit -am "Automated report"
          git push
